DROP TABLE IF EXISTS A, B, C, D, E, F CASCADE ;

CREATE TABLE A (
	a1 INTEGER PRIMARY KEY,
	a2 INTEGER
);

CREATE TABLE B (
	a1 INTEGER PRIMARY KEY REFERENCES A
		ON DELETE CASCADE,
	b1 INTEGER
);


CREATE TABLE C (
	a1 INTEGER PRIMARY KEY REFERENCES A
		ON DELETE CASCADE,
	c1 INTEGER
);

CREATE TABLE D (
	a1 INTEGER PRIMARY KEY REFERENCES B REFERENCES C
		ON DELETE CASCADE,
	d1 INTEGER
);

CREATE TABLE E (
	a1 INTEGER PRIMARY KEY REFERENCES C
		ON DELETE CASCADE,
	e1 INTEGER
);

CREATE TABLE F (
	a1 INTEGER PRIMARY KEY REFERENCES C
		ON DELETE CASCADE,
	f1 INTEGER
);