DROP TABLE IF EXISTS A, B, C, D, R, S, T CASCADE ;

CREATE TABLE A (
	a1 INTEGER PRIMARY KEY,
	a2 INTEGER,
);

CREATE TABLE B (
	b1 INTEGER PRIMARY KEY,
	b2 INTEGER,
);

CREATE TABLE C (
	c1 INTEGER PRIMARY KEY,
	c2 INTEGER,
);

CREATE TABLE D (
	d1 INTEGER PRIMARY KEY,
	d2 INTEGER,
);

CREATE TABLE R (
	a1 INTEGER,
	b1 INTEGER, 
	r1 INTEGER,
	PRIMARY KEY (a1, b1),
	FOREIGN KEY a1 REFERENCES A(a1),
	FOREIGN KEY b1 REFERENCES B(b1)
);

CREATE TABLE S (
	a1 INTEGER,
	b1 INTEGER,
	c1 INTEGER,
	s1 INTEGER,
	PRIMARY KEY (a1, b1, c1),
	FOREIGN KEY (a1, b1) REFERENCES R(a1, b1),
	FOREIGN KEY c1 REFERENCES C(c1)
);

CREATE TABLE T (
	a1 INTEGER,
	b1 INTEGER,
	c1 INTEGER,
	d1 INTEGER,
	t1 INTEGER,
	PRIMARY KEY (a1, b1, c1, d1, t1),
	FOREIGN KEY (a1, b1, c1) REFERENCES S(a1, b1, c1),
	FOREIGN KEY (d1) REFERENCES D(d1)
);